/**
 * Created by Alvin on 16/11/16.
 */

/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
* */

public class Find_the_Difference {
    public char findTheDifference(String s, String t) {
        char result = 'a';
        int[] array = new int[26];
        for (int i = 0 ; i< s.length(); i++){
            array[s.charAt(i)- 'a']++;
        }
        for(int i =0 ; i < t.length(); i++){
            array[t.charAt(i)-'a']--;
        }
        for (int i =0 ; i< array.length; i++){
            if(array[i] != 0)
                return (char)('a'+i);
        }
        return result;
    }

    public static void main(String[] args) {
        String s ="abcd";
        String t = "abcde";
        System.out.println(new Find_the_Difference().findTheDifference(s,t));
    }
}
